In [4]:
# 1. Array Creation:
# o Create a 1-dimensional array of integers from 1 to 10.
# o Create a 2-dimensional array with random float values of shape (3, 4).
# o Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [6]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
random_array = np.random.rand(3, 4)
random_array

array([[0.84457455, 0.96921744, 0.79667088, 0.71268541],
       [0.31307133, 0.70886953, 0.41316085, 0.4327455 ],
       [0.55390425, 0.13872761, 0.05607425, 0.00325893]])

In [24]:
rand_ar = np.zeros((2, 3, 4))
rand_ar

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [44]:
one = np.array([[1, 2], [3, 4]])
two = np.array([[5, 6], [7, 8]])

In [48]:
add = one + two
add

array([[ 6,  8],
       [10, 12]])

In [52]:
sub = two - one
sub

array([[4, 4],
       [4, 4]])

In [56]:
mul = one * two
mul

array([[ 5, 12],
       [21, 32]])

In [60]:
div = two / one
div

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [68]:
one_d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
one_d.mean()

5.5

In [78]:
one_d.std()

2.8722813232690143

In [80]:
np.median(one_d)

5.5

In [86]:
one_d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
two_d = one_d.reshape(3, 4)
two_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
# 3. Array Indexing and Slicing:
# o Extract the first row and last column of a 2-dimensional array.
# o Reverse the order of elements in a 1-dimensional array.
# o Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [100]:
first_r = two_d[0, : ]
first_r

array([1, 2, 3, 4])

In [96]:
last_c = two_d[:, -1]
last_c

array([ 4,  8, 12])

In [108]:
one_d = np.array([4, 2, 5, 7, 1, 9])
one_d[::-1]

array([9, 1, 7, 5, 2, 4])

In [114]:
condition = two_d % 3 == 0
new = two_d[condition]
new

array([ 3,  6,  9, 12])

In [ ]:
# 4. Array Broadcasting:
# o Add a scalar value to each element of a 2-dimensional array.
# o Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [116]:
add_2 = two_d + 2
add_2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [118]:
one_d = np.array([1, 2])
two_d = np.array([[3, 4], [5, 6]])
one_d * two_d

array([[ 3,  8],
       [ 5, 12]])

In [120]:
# 5. Linear Algebra:
# o Calculate the dot product of two 1-dimensional arrays.
# o Compute the matrix multiplication of two 2-dimensional arrays.
# o Find the inverse and determinant of a square matrix.

In [122]:
one_d = np.array([1, 2])
one_dd = np.array([1, 2])
one_d.dot(one_dd)

5

In [124]:
np.dot(one_d, one_dd)

5

In [126]:
two_d = np.array([[3, 4], [5, 6]])
two_dd = np.array([[31, 42], [53, 46]])
np.dot(two_d, two_dd)

array([[305, 310],
       [473, 486]])

In [132]:
np.linalg.det(two_d)

-2.0000000000000004

In [136]:
np.linalg.inv(two_d)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])